//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 400 core
        ///
        ///in vec3 fragColor;
        ///out vec4 outColor;
        ///
        ///void main(void)
        ///{
        ///	outColor = vec4(fragColor.xyz, 1);
        ///	//outColor = vec4(1, 0, 1, 1);
        ///}.
        /// </summary>
        internal static string graphingFragmentShader {
            get {
                return ResourceManager.GetString("graphingFragmentShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 400 core
        ///
        ///in vec3 position;
        ///in vec3 color;
        ///
        ///out vec3 fragColor;
        ///
        ///uniform vec3 dynamicColor;
        ///uniform mat4 transformationMatrix;
        ///uniform mat4 projectionMatrix;
        ///uniform mat4 viewMatrix;
        ///
        ///void main(void)
        ///{
        ///	vec4 worldPosition = transformationMatrix * vec4(position, 1);
        ///	gl_Position = projectionMatrix * viewMatrix * worldPosition;
        ///	gl_PointSize = 5;
        ///
        ///	fragColor = dynamicColor;
        ///}.
        /// </summary>
        internal static string graphingVertexShader {
            get {
                return ResourceManager.GetString("graphingVertexShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 400 core
        ///precision highp float;
        ///
        /////out vec4 outColor;
        ///in vec2 fragComplex;
        ///
        ///
        ///void main(void)
        ///{
        ///	float real = 0;
        ///	float imaginary = 0;
        ///	
        ///	float escapeRadiusSquared = 4;
        ///	int maxIterations = 100;
        ///	float zMagnitudeSquared = 0;
        ///	int iterations = 0;
        ///
        ///	while (zMagnitudeSquared &lt; escapeRadiusSquared &amp;&amp; iterations &lt; maxIterations)
        ///	{
        ///		//real = abs(real);
        ///		//imaginary = abs(imaginary);
        ///
        ///		float complexSquareReal = real * real - imaginary * imaginary;
        ///		float complexSquareImaginary = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mandelbrotFragmentShader {
            get {
                return ResourceManager.GetString("mandelbrotFragmentShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 400 core
        ///precision highp float;
        ///
        /////out vec4 outColor;
        ///in dvec2 fragComplex;
        ///
        ///
        ///void main(void)
        ///{
        ///	double real = 0;
        ///	double imaginary = 0;
        ///	
        ///	double escapeRadiusSquared = 4;
        ///	int maxIterations = 100;
        ///	double zMagnitudeSquared = 0;
        ///	int iterations = 0;
        ///
        ///	while (zMagnitudeSquared &lt; escapeRadiusSquared &amp;&amp; iterations &lt; maxIterations)
        ///	{
        ///		//real = abs(real);
        ///		//imaginary = abs(imaginary);
        ///
        ///		double complexSquareReal = real * real - imaginary * imaginary;
        ///		double complexSquareImag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mandelbrotFragmentShaderDouble {
            get {
                return ResourceManager.GetString("mandelbrotFragmentShaderDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 400 core
        ///
        ///in vec3 position;
        ///in vec2 complex;
        ///
        ///uniform mat4 transformationMatrix;
        ///uniform vec2 mousePosition;
        ///
        ///out vec2 fragComplex;
        ///
        ///void main(void)
        ///{
        ///	gl_Position = vec4(position, 1);
        ///
        ///	vec4 transformedComplex = transformationMatrix * vec4(complex, 0, 1);
        ///
        ///	fragComplex = transformedComplex.xy;
        ///}.
        /// </summary>
        internal static string mandelbrotVertexShader {
            get {
                return ResourceManager.GetString("mandelbrotVertexShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 400 core
        ///
        ///in vec3 position;
        ///in dvec2 complex;
        ///
        ///uniform dmat4 transformationMatrix;
        ///uniform vec2 mousePosition;
        ///
        ///out dvec2 fragComplex;
        ///
        ///void main(void)
        ///{
        ///	gl_Position = vec4(position, 1);
        ///
        ///	dvec4 transformedComplex = transformationMatrix * dvec4(complex, 0, 1);
        ///
        ///	fragComplex = transformedComplex.xy;
        ///}.
        /// </summary>
        internal static string mandelbrotVertexShaderDouble {
            get {
                return ResourceManager.GetString("mandelbrotVertexShaderDouble", resourceCulture);
            }
        }
    }
}
